#!/usr/bin/env bash

echo -e "Setting up Hyprland...\n"

#### Check for yay ####
ISYAY=/sbin/yay
if [ -f "$ISYAY" ]; then
    echo -e "$COK - yay was located, moving on."
    yay -Suy
else
    echo -e "$CWR - Yay was NOT located"
    read -n1 -rep $'[\e[1;33mACTION\e[0m] - Would you like to install yay (y,n) ' INSTYAY
    if [[ $INSTYAY == "Y" || $INSTYAY == "y" ]]; then
        git clone https://aur.archlinux.org/yay.git
        cd yay
        makepkg -si --noconfirm
        cd ..
    else
        echo -e "$CER - Yay is required for this script, now exiting"
        exit
    fi
fi

### Install all of the required pacakges ####
read -n1 -rep 'Would you like to install the required packages? (y,n)' INSTDEPS
if [[ $INSTDEPS == "Y" || $INSTDEPS == "y" ]]; then
    yay -S --noconfirm \
        brave-bin \
        brightnessctl \
        dunst \
        ffmpeg \
        fish \
        grimblast-git \
        hyprkeys \
        hyprland-autoname-workspaces \
        hyprland-git \
        jq \
        hyprpicker-git \
        kitty \
        neovim \
        network-manager-applet \
        noto-fonts \
        noto-fonts-emoji \
        pacman-contrib \
        nwg-look-bin \
        pamixer \
        pavucontrol \
        playerctl \
        polkit-gnome \
        python-requests \
        rofi \
        rofi-emoji \
        sddm-git \
        swaybg \
        swaylock-effects \
        swayosd-git \
        thunar \
        ttf-iosevka \
        ttf-iosevka-nerd \
        ttf-iosevka-term \
        ttf-nerd-fonts-symbols-common \
        waybar-hyprland \
        wf-recorder \
        wl-clipboard \
        wlogout \
        wlsunset \
        xdg-portal-hyprland
fi

### Install all of the optional pacakges ####
read -n1 -rep 'Would you like to install the optional packages? (y,n)' INSTOPT
if [[ $INSTOPT == "Y" || $INSTOPT == "y" ]]; then
    yay -S --noconfirm \
        discord \
        dropbox \
        gimp \
        kdenlive \
        steam
fi

### Set the config files ###
read -n1 -rep 'Would you like to copy config files? (y,n)' CFG
if [[ $CFG == "Y" || $CFG == "y" ]]; then
    unlink ~/.config/hypr 2> /dev/null || rm -rf ~/.config/hypr
    ln -s $(pwd)/hypr ~/.config/hypr
    mkdir -p ~/.config/hypr/themes/dist
    touch ~/.config/hypr/themes/dist/dist.conf

    unlink ~/.config/hyprland-autoname-workspaces 2> /dev/null || rm -rf ~/.config/hyprland-autoname-workspaces
    ln -s $(pwd)/hyprland-autoname-workspaces ~/.config/hyprland-autoname-workspaces
fi

### Set the theme ###
read -n1 -rep 'Would you like to install hyprtheme? (y,n)' INSTHT
if [[ $INSTHT == "Y" || $INSTHT == "y" ]]; then
    git clone https://github.com/hyprland-community/hyprtheme
    cd hyprtheme
    make all
    cd ..

    mkdir -p ~/.config/hypr/themes
fi

if command -v hyprtheme &> /dev/null
then
    read -n1 -rep 'What theme would you like to set: default (0), breaking-bad (1), darker (2)?' THEME
    if [[ $THEME == "1" ]]; then
        git clone https://github.com/alexjercan/breakingbad-hyprland-theme.git ~/.config/hypr/themes/breakingbad-hyprland-theme
        bash ~/.config/hypr/themes/breakingbad-hyprland-theme/install
        hyprtheme apply breakingbad-hyprland-theme
    elif [[ $THEME == "2" ]]; then
        git clone https://github.com/alexjercan/darker-hyprland-theme.git ~/.config/hypr/themes/darker-hyprland-theme
        bash ~/.config/hypr/themes/darker-hyprland-theme/install
        hyprtheme apply darker-hyprland-theme
    fi
fi

### Script is done ###
echo -e "Script had completed.\n"
