#!/usr/bin/env bash

unlink ~/.config/hypr 2> /dev/null || rm -rf ~/.config/hypr
ln -s $(pwd)/hypr ~/.config/hypr

unlink ~/.config/waybar 2> /dev/null || rm -rf ~/.config/waybar/
ln -s $(pwd)/waybar ~/.config/waybar

unlink ~/.config/dunst 2> /dev/null || rm -rf ~/.config/dunst/
ln -s $(pwd)/dunst ~/.config/dunst

unlink ~/.config/rofi 2> /dev/null || rm -rf ~/.config/rofi/
ln -s $(pwd)/rofi ~/.config/rofi

unlink ~/.config/swaylock/ 2> /dev/null || rm -rf ~/.config/swaylock/
ln -s $(pwd)/swaylock ~/.config/swaylock

unlink ~/.config/wlogout/ 2> /dev/null || rm -rf ~/.config/wlogout/
ln -s $(pwd)/wlogout ~/.config/wlogout
