#!/bin/sh

#show a message
notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Switching To Breaking Bad Theme"

#set the kitty theme
kitty +kitten themes Breaking\ Bad

#set the waybar theme
iDir="${XDG_CONFIG_HOME:=${HOME}/.config}/waybar/"
cp $iDir/themes/breaking-bad.css $iDir/current-theme.css
killall waybar
waybar &

#set the GTK theme
gsettings set org.gnome.desktop.interface gtk-theme "BreakingBad"
gsettings set org.gnome.desktop.interface icon-theme "Reversal-green-dark"

# set the background
killall swaybg
swaybg -m fill -i ~/Pictures/wallpapers/breakingbad.jpg
