[theme]
name="Default"
description="Default theme"
version = "0.1.0"
author = "alexjercan"
git = "github.com/alexjercan/hyprland.dotfiles"
depends = ["waybar", "swaybg", "rofi", "dunst"]
config = "theme.conf"

[script]
load="./load"
cleanup="./cleanup"

[kill]
exclude_bar = []
exclude_wallpaper = []
