#!/bin/bash

iDIR="$HOME/.config/dunst/icons"

# Get brightness
get_backlight() {
	LIGHT=$(printf "%.0f\n" $(brightnessctl g))
	light=$((LIGHT*100/7500))
	echo "${light}%"
}

# Get icons
get_icon() {
	current="$(brightnessctl g)"
	if [[ ("$current" -ge "0") && ("$current" -le "1500") ]]; then
		echo "$iDIR/brightness-20.png"
	elif [[ ("$current" -ge "1500") && ("$current" -le "3000") ]]; then
		echo "$iDIR/brightness-40.png"
	elif [[ ("$current" -ge "3000") && ("$current" -le "4500") ]]; then
		echo "$iDIR/brightness-60.png"
	elif [[ ("$current" -ge "4500") && ("$current" -le "6000") ]]; then
		echo "$iDIR/brightness-80.png"
	elif [[ ("$current" -ge "6000") && ("$current" -le "7500") ]]; then
		echo "$iDIR/brightness-100.png"
	fi
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Brightness : $(get_backlight)"
}

# Increase brightness
inc_backlight() {
	brightnessctl set 10%+ && get_icon && notify_user
}

# Decrease brightness
dec_backlight() {
	brightnessctl set 10%- && get_icon && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	brightnessctl g
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
